# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-Os -pipe -march=armv7-a+simd -mtune=cortex-a7 -mfloat-abi=hard -ftree-vectorize -fomit-frame-pointer -fno-semantic-interposition -fstack-protector-strong"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

USE="ssh libkms unicode ipv6 pam ssl vim mysql -postgres ntp iptables icu network vim-syntax ja cjk jp dbus -gnutls -mpi crypt -cups dri -emacs iconv libnotify -lirc mime mmap -oss -pcre session sharedmem socket udev usb acl -xemacs xml zlib inotify caps llvm gallium gbm curl -tls-heartbeat -xattr elf -mono -handbook -multilib -tcpd -inetd -xinetd systemd vulkan zstd z3 -ruby idn fuse -gpm x264 x265 jpeg png graphics fontconfig boost ffmpeg joystick -gtk -gtk2 -gtk3 -gtk-doc -handbook -hunspell -wext egl imagemagick vulkan fcitx5 -jpeg2k touchscreen tslib tuio libinput gles2 iproute2 -wayland gstreamer v4l openh264 -lto sdl -policykit kms -X -openmp -lz4 -gcrypt -sanitize -fortran -debuginfod"

MAKEOPTS="-j8"
#FEATURES="getbinpkg"
USE_PYTHON="3.13"
PYTHON_TARGETS="python3_13"
PYTHON_SINGLE_TARGET="python3_13"
VIDEO_CARDS="llvmpipe lavapipe"
LINGUAS="ja"
L10N="en ja"

